<?php
/*-------------------------------------------
   Rent Manager Settings
--------------------------------------------*/
// RM General

function my_acf_add_local_field_groups()
{
	acf_add_options_page(
		array(
			'page_title' => 'Rent Manager Settings',
			'menu_title' => 'Rent Manager Settings',
			'menu_slug' => 'rentmanager-settings',
			'capability' => 'edit_posts',
			'redirect' => false
		)
	);


	acf_add_local_field_group(
		array(
			'key' => 'rm_general_info',
			'title' => 'General Info',
			'fields' => array(
				array(
					'key' => 'group_general',
					'label' => 'General',
					'name' => '',
					'type' => 'tab',
					'instructions' => 'Enter your Rent Manager information to allow your website to integrate with your listings',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'general1',
					'label' => 'Company Code',
					'name' => 'co_code',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'lcs-ps122',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'general2',
					'label' => 'Property Filter',
					'name' => 'prop_filter',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'show_on_website',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'general3',
					'label' => 'Unit Filter',
					'name' => 'unit_filter',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'show_on_website',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'general7',
					'label' => 'Featured Filter',
					'name' => 'featured_filter',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'isFeatured',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'general5',
					'label' => 'Unit Template',
					'name' => 'unit_temp',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'unitDefault',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'general6',
					'label' => 'Property Template',
					'name' => 'prop_temp',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'propertyDefault',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				
				array(
					'key' => 'general4',
					'label' => 'Locations',
					'name' => 'rm_location',
					'type' => 'text',
					'instructions' => 'Add as comma seperated names. Ex. default,secondary<br>Make sure to add UA profiles to both locations.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
				),
				
				array(
					'key' => 'general8',
					'label' => 'Default Listing Image',
					'name' => 'default_listing_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'general9',
					'label' => 'Default Detail Image',
					'name' => 'default_detail_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				//UA Pull Setup
				array(
					'key' => 'group_UA',
					'label' => 'Unit Availability',
					'type' => 'tab',
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield0',
					'type' => 'message',
					'message' => '<p>These choices will control how the listings are pulled out of Rent Manager.</p>',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield1',
					'label' => 'UA Primary Date Type',
					'name' => 'uaPrimary',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'choices' => array(
						'moveOut' => 'Move Out Date',
						'expected' => 'Expected Move Out Date',
						'notice' => 'Notice Date',
						'udf' => 'User Defined Field'
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield2',
					'label' => 'UA Secondary Date Type',
					'name' => 'uaSecondary',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'choices' => array(
						'moveOut' => 'Move Out Date',
						'expected' => 'Expected Move Out Date',
						'notice' => 'Notice Date',
						'udf' => 'User Defined Field'
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield3',
					'label' => 'UA Fallback Date Type',
					'name' => 'uaFallback',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'choices' => array(
						'moveOut' => 'Move Out Date',
						'expected' => 'Expected Move Out Date',
						'notice' => 'Notice Date',
						'udf' => 'User Defined Field'
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield4',
					'label' => 'UA Date User Defined Field',
					'name' => 'uaUDF',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,

					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'uafield5',
					'label' => 'Days to add to availability',
					'name' => 'unitListAvailDays',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				//Property Tab
				array(
					'key' => 'group_property',
					'label' => 'Property Listing',
					'name' => '',
					'type' => 'tab',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'propfield1',
					'label' => 'Property Name',
					'name' => 'propName',
					'type' => 'text',
					'instructions' => 'Put in the field to use as udfname, removing all spaces and special characters and use all lowercase',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'webpropertyname',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield2',
					'label' => 'Property Listing Main Title',
					'name' => 'propListTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'propName',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield3',
					'label' => 'Property Listing Sub Title',
					'name' => 'propListSubTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'pstreet',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield4',
					'label' => '',
					'name' => 'propListType',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Type on Listing',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'propfield5',
					'label' => '',
					'name' => 'propListApplyNow',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Apply Now',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield6',
					'label' => '',
					'name' => 'propListMojo',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Show Mojo',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield7',
					'label' => '',
					'name' => 'propDetailLink',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Link to Property Detail Page?',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propfield8',
					'label' => 'Property Detail Page',
					'name' => 'propDetailPage',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'propfield7',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'post_type' => 'page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

//Property Detail Tab
				array(
					'key' => 'group_propDetail',
					'label' => 'Property Detail',
					'name' => '',
					'type' => 'tab',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'propDetail1',
					'label' => 'Property Detail Main Title',
					'name' => 'propDetailTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'property->propName',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail2',
					'label' => 'Property Detail Sub Title',
					'name' => 'propDetailSubTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as >fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'property->pstreet',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail3',
					'label' => '',
					'name' => 'propApplyNow',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Apply Now',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'propDetail4',
					'label' => '',
					'name' => 'propMojo',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Show Mojo',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'propDetail5',
					'label' => '',
					'name' => 'propDetailPhotos',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Photos on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail6',
					'label' => '',
					'name' => 'propDetailType',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Type on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail7',
					'label' => '',
					'name' => 'propDetailManager',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Manager on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail8',
					'label' => '',
					'name' => 'propDetailAmenities',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Amenities on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'propDetail9',
					'label' => '',
					'name' => 'propDetailTour',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Video Tour on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'propDetail10',
					'label' => '',
					'name' => 'propDetailMap',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Google Map on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail11',
					'label' => '',
					'name' => 'propDetailUnits',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Unit Listings on Property Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'propDetail12',
					'label' => 'Unit Listing Title',
					'name' => 'propDetailUnitTitle',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'propDetail11',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),


//Unit Listing Tab
				array(
					'key' => 'group_unitList',
					'label' => 'Unit Listing',
					'name' => '',
					'type' => 'tab',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'unitfield1',
					'label' => 'Unit Listing Main Title',
					'name' => 'unitListTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as $unit->fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '$unit->unitName',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitfield2',
					'label' => 'Unit Listing Sub Title',
					'name' => 'unitListSubTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as $unit->fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '$unit->street',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitfield3',
					'label' => '',
					'name' => 'unitListApply',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Apply Now',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitfield4',
					'label' => '',
					'name' => 'unitListMojo',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display ShowMojo',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitfield5',
					'label' => '',
					'name' => 'unitListProp',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Link on Listing',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitfield6',
					'label' => '',
					'name' => 'unitListDetail',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Link to Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitfield7',
					'label' => 'Unit Detail Page',
					'name' => 'unitDetailPage',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'unitfield6',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'post_type' => 'page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),



				//Unit Detail Tab
				array(
					'key' => 'group_unitDetail',
					'label' => 'Unit Detail',
					'name' => '',
					'type' => 'tab',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
				),
				array(
					'key' => 'unitdetail1',
					'label' => 'Unit Detail Main Title',
					'name' => 'unitDetailTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '$unit->unitName',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitdetail2',
					'label' => 'Unit Detail Sub Title',
					'name' => 'unitDetailSubTitle',
					'type' => 'text',
					'instructions' => 'Put in the field to use as $unit->fieldname',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '$unit->street',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitdetail3',
					'label' => '',
					'name' => 'unitDetailApply',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Apply Now',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitdetail4',
					'label' => '',
					'name' => 'unitDetailMojo',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display ShowMojo',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitdetail5',
					'label' => '',
					'name' => 'unitDetailProp',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Link',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitdetail6',
					'label' => '',
					'name' => 'unitDetailPropDesc',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Description',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitdetail7',
					'label' => '',
					'name' => 'unitDetailPropTour',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Property Video Tour on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitdetail8',
					'label' => '',
					'name' => 'unitDetailTour',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Unit Video Tour on Detail Page',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

				array(
					'key' => 'unitdetail9',
					'label' => '',
					'name' => 'unitDetailMap',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'message' => 'Display Google Map',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'unitdetail10',
					'label' => '',
					'name' => 'unitDetailMapProp',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'unitdetail9',
								'operator' => '==',
								'value' => 1,
							),
						),
					),
					'wrapper' => array(
						'width' => '33',
						'class' => '',
						'id' => '',
					),
					'default_value' => 0,
					'message' => 'Use Property Address for Map',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),

			),
			'location' => array(
				array(
					array(
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'rentmanager-settings',
					),
				),
			),

			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		)
	);
}



add_action('acf/init', 'my_acf_add_local_field_groups');