<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
    <meta charset="<?php bloginfo( 'charset' ); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Title is automatically generated by WordPress -->
    <title><?php echo get_hoa_var('hoa_name'); ?> | Managed by <?php echo get_hoa_var('management_name'); ?></title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    
    <!-- IMPORTANT: This hook lets WordPress load your style.css, Tailwind, and plugins -->
    <?php wp_head(); ?>
</head>
<body <?php body_class("min-h-screen flex flex-col antialiased"); ?>>

    <!-- Header -->
    <header class="bg-white shadow-xl sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
            
            <div class="flex items-end space-x-4">
                <h1 class="text-3xl font-extrabold text-gray-900 leading-none"><?php echo get_hoa_var('hoa_name'); ?></h1>
                <p class="text-xs font-semibold text-gray-500 hidden sm:block mb-1">Managed by <?php echo get_hoa_var('management_name'); ?></p>
            </div>
            
            <a href="<?php echo get_hoa_var('management_url'); ?>" target="_blank" class="flex items-center space-x-2 group">
                 <!-- Updated Logo URL -->
                 <img src="https://advancedrealty.com/wp-content/uploads/2025/11/JPG-Advanced-Realty-Logo.jpg" 
                      onerror="this.style.display='none'; document.getElementById('logo-text-fallback-hoa').classList.remove('hidden');"
                      alt="Management Logo" class="h-12 opacity-80 group-hover:opacity-100 transition duration-150">
                <span id="logo-text-fallback-hoa" class="text-xl font-extrabold text-adv-teal hidden"><?php echo strtoupper(get_hoa_var('management_name')); ?></span>
            </a>
        </div>
    </header>
    
    <!-- Main Content Area Begins -->
    <main class="flex-grow">